package com.waffle.demo.config;

import lombok.Getter;

/**
 * 에러 코드 관리
 */
@Getter
public enum BaseResponseStatus {
    // 1000 : 요청 성공
    SUCCESS(true, 1000, "요청에 성공하였습니다."),
    SUCCESS_READ_USERS(true, 1010, "전체 회원 정보 조회에 성공하였습니다."),
    SUCCESS_READ_USER(true, 1011, "회원 정보 조회에 성공하였습니다."),
    SUCCESS_POST_USER(true, 1012, "회원가입에 성공하였습니다."),
    SUCCESS_LOGIN(true, 1013, "로그인에 성공하였습니다."),
    SUCCESS_JWT(true, 1014, "JWT 검증에 성공하였습니다."),
    SUCCESS_DELETE_USER(true, 1015, "회원 탈퇴에 성공하였습니다."),
    SUCCESS_PATCH_USER(true, 1016, "회원정보 수정에 성공하였습니다."),
    SUCCESS_READ_ALBUMS(true, 1020, "전체 앨범 정보 조회에 성공하였습니다."),
    SUCCESS_READ_ALBUM(true, 1021, "앨범 정보 조회에 성공하였습니다."),
    SUCCESS_POST_ALBUM(true, 1022, "앨범 등록에 성공하였습니다."),
    SUCCESS_PATCH_ALBUM(true, 1023, "앨범 정보 수정에 성공하였습니다."),
    SUCCESS_DELETE_ALBUM(true, 1024, "앨범 삭제에 성공하였습니다."),
    SUCCESS_READ_MUSICS(true, 1030, "전체 음악 정보 조회에 성공하였습니다."),
    SUCCESS_READ_MUSIC(true, 1031, "음악 정보 조회에 성공하였습니다."),
    SUCCESS_POST_MUSIC(true, 1032, "음악 등록에 성공하였습니다."),
    SUCCESS_PATCH_MUSIC(true, 1033, "음악 정보 수정에 성공하였습니다."),
    SUCCESS_DELETE_MUSIC(true, 1034, "음악 삭제에 성공하였습니다."),
    SUCCESS_READ_SINGERS(true, 1040, "전체 가수 정보 조회에 성공하였습니다."),
    SUCCESS_READ_SINGER(true, 1041, "가수 정보 조회에 성공하였습니다."),
    SUCCESS_POST_SINGER(true, 1042, "가수 등록에 성공하였습니다."),
    SUCCESS_PATCH_SINGER(true, 1043, "가수 정보 수정에 성공하였습니다."),
    SUCCESS_DELETE_SINGER(true, 1044, "가수 삭제에 성공하였습니다."),
    SUCCESS_READ_SINGERMUSICS(true, 1050, "가수 곡 목록 조회에 성공하였습니다."),
    SUCCESS_READ_SINGERALBUMS(true, 1060, "가수 앨범 목록 조회에 성공하였습니다."),
    SUCCESS_POST_SINGERLIKE(true, 1072, "가수 좋아요 생성에 성공하였습니다."),
    SUCCESS_DELETE_SINGERLIKE(true, 1073, "가수 좋아요 취소에 성공하였습니다."),
    SUCCESS_POST_MUSICLIKE(true, 1082, "음악 좋아요 생성에 성공하였습니다."),
    SUCCESS_DELETE_MUSICLIKE(true, 1083, "음악 좋아요 취소에 성공하였습니다."),
    SUCCESS_POST_ALBUMLIKE(true, 1092, "앨범 좋아요 생성에 성공하였습니다."),
    SUCCESS_DELETE_ALBUMLIKE(true, 1093, "앨범 좋아요 취소에 성공하였습니다."),
    SUCCESS_POST_ALBUMRATE(true, 1102, "앨범 평점 생성에 성공하였습니다."),
    SUCCESS_READ_VOUCHER(true, 1110, "이용권 조회에 성공하였습니다."),
    SUCCESS_POST_VOUCHER(true, 1111, "이용권 등록에 성공하였습니다."),
    SUCCESS_PATCH_VOUCHER(true, 1112, "이용권 수정에 성공하였습니다."),
    SUCCESS_DELETE_VOUCHER(true, 1113,"이용권 삭제에 성공하였습니다."),
    SUCCESS_POST_USERVOUCHER(true, 1121, "유저 이용권 생성에 성공하였습니다."),
    SUCCESS_DELETE_USERVOUCHER(true, 1131, "유저 이용권 삭제에 성공하였습니다."),
    SUCCESS_READ_SINGERCHANNEL(true, 1140, "가수 채널 조회에 성공하였습니다."),
    SUCCESS_READ_SINGERCOMMENT(true, 1150, "가수 댓글 목록 조회에 성공하였습니다."),
    SUCCESS_POST_SINGERCOMMENT(true,1151,"가수 댓글 생성에 성공하였습니다."),
    SUCCESS_PATCH_SINGERCOMMENT(true, 1152, "가수 댓글 수정에 성공하였습니다."),
    SUCCESS_DELETE_SINGERCOMMENT(true, 1153, "가수 댓글 삭제에 성공하였습니다."),
    SUCCESS_READ_SINGERRECOMMENT(true, 1160, "가수 대댓글 목록 조회에 성공하였습니다."),
    SUCCESS_POST_SINGERRECOMMENT(true,1161,"가수 대댓글 생성에 성공하였습니다."),
    SUCCESS_PATCH_SINGERRECOMMENT(true, 1162, "가수 대댓글 수정에 성공하였습니다."),
    SUCCESS_DELETE_SINGERRECOMMENT(true, 1163, "가수 대댓글 삭제에 성공하였습니다."),
    SUCCESS_POST_SINGERCOMMENTLIKE(true, 1171, "가수 댓글 좋아요 생성에 성공하였습니다."),
    SUCCESS_DELETE_SINGERCOMMENTLIKE(true, 1173, "가수 댓글 좋아요 취소에 성공하였습니다."),
    SUCCESS_POST_SINGERCOMMENTHATE(true, 1181, "가수 댓글 싫어요 생성에 성공하였습니다."),
    SUCCESS_DELETE_SINGERCOMMENTHATE(true, 1183, "가수 댓글 싫어요 취소에 성공하였습니다."),
    SUCCESS_READ_ALBUMCHANNEL(true, 1190, "앨범 채널 조회에 성공하였습니다."),
    SUCCESS_READ_MUSICCHANNEL(true, 1200, "음악 채널 조회에 성공하였습니다."),
    SUCCESS_READ_CURRENTPLAYMUSIC(true, 1210, "현재 재생 곡 조회에 성공하였습니다."),
    SUCCESS_POST_CURRENTPLAYMUSIC(true, 1211, "현재 재생 곡 생성에 성공하였습니다."),
    SUCCESS_READ_CURRENTPLAYLIST(true, 1220, "현재 재생 목록 조회에 성공하였습니다."),
    SUCCESS_POST_CURRENTPLAYLIST(true, 1221, "현재 재생 목록 생성에 성공하였습니다."),
    SUCCESS_PATCH_CURRENTPLAYLIST(true, 1222, "현재 재생 목록 수정에 성공하였습니다."),
    SUCCESS_DELETE_CURRENTPLAYLIST(true, 1223, "현재 재생 목록 삭제에 성공하였습니다."),

    // 2000 : Request 오류
    REQUEST_ERROR(false, 2000, "입력값을 확인해주세요."),
    EMPTY_USERIDX(false, 2001, "유저 인덱스 값을 확인해주세요."),
    EMPTY_JWT(false, 2010, "JWT를 입력해주세요."),
    INVALID_JWT(false, 2011, "유효하지 않은 JWT입니다."),
    EMPTY_ID(false, 2020, "아이디를 입력해주세요."),
    EMPTY_PASSWORD(false, 2030, "비밀번호를 입력해주세요."),
    EMPTY_CONFIRM_PASSWORD(false, 2031, "비밀번호 확인을 입력해주세요."),
    WRONG_PASSWORD(false, 2032, "비밀번호를 다시 입력해주세요."),
    DO_NOT_MATCH_PASSWORD(false, 2033, "비밀번호와 비밀번호확인 값이 일치하지 않습니다."),
    EMPTY_NICKNAME(false, 2040, "닉네임을 입력해주세요."),
    EMPTY_PHONENUM(false, 2050, "연락처를 입력해주세요."),
    INVALID_PHONENUM(false, 2051, "연락처 형식을 확인해주세요."),
    EMPTY_GENDER(false, 2060, "성별을 입력해주세요."),
    WRONG_GENDER(false, 2061, "성별 값은 F(여성)/M(남성)/C(혼성)으로 입력해주세요."),
    EMPTY_ALBUMIDX(false, 2070, "앨범 인덱스 값을 확인해주세요."),
    EMPTY_MUSICIDX(false, 2080, "음악 인덱스 값을 확인해주세요."),
    EMPTY_SINGERIDX(false, 2090, "가수 인덱스 값을 확인해주세요."),
    EMPTY_ALBUMTITLE(false, 2100, "앨범 제목 값을 확인해주세요."),
    EMPTY_RELEASEDATE(false, 2110, "발매일 값을 확인해주세요."),
    EMPTY_RELEASECOMPANY(false, 2120, "발매사 값을 확인해주세요."),
    EMPTY_GENRE(false, 2130, "장르 값을 확인해주세요."),
    EMPTY_ALBUMTYPE(false, 2140, "앨범 유형 값을 확인해주세요."),
    EMPTY_SINGERNAME(false, 2150, "가수 이름 값을 확인해주세요."),
    EMPTY_NATIONALITY(false, 2160, "국적을 입력해주세요."),
    EMPTY_SINGERTYPE(false, 2170, "가수 유형 값을 확인해주세요."),
    EMPTY_AGENCY(false, 2180, "소속사/기획사 값을 확인해주세요."),
    EMPTY_MUSICTITLE(false, 2190, "음악 제목을 입력해주세요."),
    EMPTY_WRITING(false, 2200, "작사가를 입력해주세요."),
    EMPTY_COMPOSING(false, 2210, "작곡가를 입력해주세요."),
    EMPTY_ARRANGING(false, 2220, "편곡자를 입력해주세요."),
    EMPTY_MUSICLENGTH(false, 2230, "음악 길이를 입력해주세요."),
    EMPTY_MUSICURL(false, 2240, "음악 파일을 첨부해주세요."),
    EMPTY_ISTITLE(false, 2250, "타이틀 곡인지 여부를 입력해주세요."),
    WRONG_ISTITLE(false, 2251, "타이틀 곡인지 Y 혹은 N의 값으로 입력해주세요."),
    EMPTY_TYPE(false,2260, "해당 가수가 앨범에 참여한 유형을 입력해주세요."),
    EMPTY_ISSINGER(false, 2270, "해당 가수가 앨범의 주인인지 입력해주세요."),
    WRONG_ISSINGER(false, 2271, "해당 가수가 앨범의 주인인지 Y 혹은 N의 값으로 입력해주세요."),
    NOT_ENOUGH_ALBUMSINGER_INFO(false, 2280, "앨범의 가수 정보 수가 알맞지 않습니다."),
    NOT_ENOUGH_MUSICSINGER_INFO(false, 2290, "음악의 가수 정보 수가 알맞지 않습니다."),
    EMPTY_EMAIL(false, 2300, "이메일을 입력해주세요."),
    INVALID_EMAIL(false, 2301, "이메일 형식을 확인해주세요."),
    EMPTY_AUTHENTICATION(false, 2310, "본인 인증 여부를 입력해주세요."),
    WRONG_AUTHENTICATION(false, 2311, "본인 인증 여부 값을 Y 혹은 N으로 입력해주세요."),
    EMPTY_ALBUMRATE(false, 2320, "앨범 평점을 입력해주세요."),
    EMPTY_VOUCHERNAME(false, 2330, "이용권 이름을 입력해주세요."),
    EMPTY_VOUCHERPRICE(false, 2340, "이용권 가격을 입력해주세요."),
    EMPTY_VOUCHERIDX(false, 2350, "이용권 인덱스를 확인해주세요."),
    EMPTY_USERVOUCHERIDX(false, 2360, "유저 이용권 인덱스를 확인해주세요."),
    EMPTY_SINGERCOMMENT(false, 2370, "가수 댓글을 입력해주세요."),
    EMPTY_COMMENTIDX(false, 2380, "댓글 인덱스를 확인해주세요."),
    EMPTY_LIKE(false, 2390,"좋아요/싫어요를 입력해주세요."),
    WRONG_LIKE(false, 2391, "좋아요는 L, 싫어요는 H로 입력해주세요."),
    EMPTY_HASSTREAMING(false, 2400, "스트리밍 포함 여부를 입력해주세요."),
    WRONG_HASSTREAMING(false, 2401,"스트리밍 포함 여부를 Y 혹은 N으로 입력해주세요."),
    EMPTY_HASDOWNLOAD(false, 2410, "다운로드 포함 여부를 입력해주세요."),
    WRONG_HASDOWNLOAD(false, 2411,"다운로드 포함 여부를 Y 혹은 N으로 입력해주세요."),
    EMPTY_CHANNELNAME(false, 2420,"채널 제목을 입력하세요."),
    EMPTY_PROFILEMUSICIDX(false, 2430,"프로필 음악 인덱스를 입력하세요."),
    EMPTY_PROFILEIMGURL(false, 2440,"프로필 사진을 첨부하세요."),
    EMPTY_CAREER(false, 2450,"수상 이력을 입력하세요."),
    EMPTY_SINGERINTRODUCTION(false, 2460,"소개글을 입력하세요."),
    EMPTY_OFFICIALSITE(false, 2470,"공식 사이트 주소를 입력하세요."),
    EMPTY_FACEBOOK(false, 2480,"페이스북 사이트를 입력하세요."),
    EMPTY_TWITTER(false, 2490,"트위터 주소를 입력하세요."),
    EMPTY_INSTAGRAM(false, 2500,"인스타그램 주소를 입력하세요."),
    EMPTY_MEMBER(false, 2510,"멤버를 입력하세요."),
    EMPTY_GROUP(false, 2520,"소속그룹/유닛을 입력하세요."),
    EMPTY_ALBUMIMGURL(false, 2530,"앨컴 커버 이미지를 첨부하세요."),
    EMPTY_ALBUMINTRODUCTION(false, 2520,"앨범 소개글을 입력하세요."),
    EMPTY_LYRIC(false, 2520,"음악 가사를 입력하세요."),
    EMPTY_CREATETYPE(false, 2530,"재생 곡 담기 타입을 선택하세요."),
    WRONG_CREATETYPE(false, 2531, "재생 곡 담기 타입을 0(맨 처음), 1(재생곡 바로 뒤), 2(맨 끝)로 입력하여주세요."),
    EMPTY_CURRENTPLAYLISTMUSICIDX(false, 2540,"현재 재생 목록 곡 인덱스를 입력하세요."),
    DO_NOT_MATCH_MUSICCNT(false, 2053, "현재 재생 곡 수와 입력한 인덱스 수가 일치하지 않습니다."),

    // 3000 : Response 오류
    RESPONSE_ERROR(false, 3000, "값을 불러오는데 실패하였습니다."),
    NOT_FOUND_USER(false, 3010, "존재하지 않는 회원입니다."),
    DUPLICATED_USER(false, 3011, "이미 존재하는 회원입니다."),
    FAILED_TO_GET_USER(false, 3012, "회원 정보 조회에 실패하였습니다."),
    FAILED_TO_POST_USER(false, 3013, "회원가입에 실패하였습니다."),
    FAILED_TO_LOGIN(false, 3014, "로그인에 실패하였습니다."),
    FAILED_TO_DELETE_USER(false, 3015, "회원 탈퇴에 실패하였습니다."),
    FAILED_TO_PATCH_USER(false, 3016, "개인정보 수정에 실패하였습니다."),
    NOT_FOUND_ALBUM(false, 3020, "존재하지 않는 앨범입니다."),
    FAILED_TO_GET_ALBUM(false, 3022, "앨범 정보 조회에 실패하였습니다."),
    FAILED_TO_POST_ALBUM(false, 3023, "앨범 등록에 실패하였습니다."),
    FAILED_TO_PATCH_ALBUM(false, 3024, "앨범 정보 수정에 실패하였습니다."),
    FAILED_TO_DELETE_ALBUM(false, 3025, "앨범 삭제에 실패하였습니다."),
    NOT_FOUND_MUSIC(false, 3030, "존재하지 않는 곡입니다."),
    FAILED_TO_GET_MUSIC(false, 3032, "음악 정보 조회에 실패하였습니다."),
    FAILED_TO_POST_MUSIC(false, 3033, "음악 등록에 실패하였습니다."),
    FAILED_TO_PATCH_MUSIC(false, 3034, "음악 정보 수정에 실패하였습니다."),
    FAILED_TO_DELETE_MUSIC(false, 3035, "음악 삭제에 실패하였습니다."),
    NOT_FOUND_SINGER(false, 3040, "존재하지 않는 가수입니다."),
    FAILED_TO_GET_SINGER(false, 3042, "가수 정보 조회에 실패하였습니다."),
    FAILED_TO_POST_SINGER(false, 3043, "가수 등록에 실패하였습니다."),
    FAILED_TO_PATCH_SINGER(false, 3044, "가수 정보 수정에 실패하였습니다."),
    FAILED_TO_DELETE_SINGER(false, 3045, "가수 삭제에 실패하였습니다."),
    NOT_FOUND_GENRE(false, 3050, "존재 하지 않는 장르입니다."),
    FAILED_TO_GET_GENRE(false, 3052, "장르 정보 조회에 실패하였습니다."),
    FAILED_TO_GET_ALBUMSINGER(false, 3062, "앨범 가수 정보 조회에 실패하였습니다."),
    FAILED_TO_GET_MUSICSINGER(false, 3072, "음악 가수 정보 조회에 실패하였습니다."),
    FAILED_TO_ACCESS(false, 3080, "권한이 없는 유저입니다."),
    FAILED_TO_POST_SINGERLIKE(false, 3093, "가수 좋아요 생성에 실패하엿습니다."),
    FAILED_TO_DELETE_SINGERLIKE(false, 3094, "가수 좋아요 취소에 실패하였습니다."),
    FAILED_TO_POST_MUSICLIKE(false, 3103, "음악 좋아요 생성에 실패하였습니다."),
    FAILED_TO_DELETE_MUSICLIKE(false, 3104, "음악 좋아요 취소에 실패하였습니다."),
    FAILED_TO_POST_ALBUMLIKE(false, 3113, "앨범 좋아요 생성에 실패하였습니다."),
    FAILED_TO_DELETE_ALBUMLIKE(false, 3114, "앨범 좋아요 취소에 실패하였습니다."),
    FAILED_TO_POST_ALBUMRATE(false, 3123, "앨범 평점 생성에 싪패하였습니다."),
    DUPLICATED_ALBUMRATE(false, 3121, "이미 앨범 평점을 등록하였습니다."),
    NOT_FOUND_VOUCHER(false, 3130, "존재하지 않는 이용권입니다."),
    FAILED_TO_GET_VOUCHER(false,3132, "이용권 조회에 실패하였습니다."),
    FAILED_TO_POST_VOUCHER(false, 3133, "이용권 등록에 실패하였습니다."),
    FAILED_TO_PATCH_VOUCHER(false, 3134, "이용권 수정에 실패하였습니다."),
    FAILED_TO_DELETE_VOUCHER(false, 3135, "이용권 삭제에 실패하였습니다."),
    NOT_FOUND_USERVOUCHER(false, 3140, "존재하지 않는 유저 이용권입니다."),
    DUPLICATED_USERVOUCHER(false, 3141, "이미 존재하는 이용권입니다."),
    FAILED_TO_GET_USERVOUCHER(false, 3142, "유저 이용권 조회에 실패하였습니다."),
    FAILED_TO_POST_USERVOUCHER(false, 3143, "유저 이용권 등록에 실패하였습니다."),
    FAILED_TO_DELETE_USERVOUCHER(false, 3145, "유저 이용권 삭제에 실패하였습니다."),
    FAILED_TO_GET_SINGERCOMMENT(false, 3152, "가수 댓글 조회에 실패하였습니다."),
    FAILED_TO_POST_SINGERCOMMENT(false, 3153, "가수 댓글 생성에 실패하였습니다."),
    FAILED_TO_PATCH_SINGERCOMMENT(false, 3154, "가수 댓글 수정에 실패하였습니다."),
    FAILED_TO_DELETE_SINGERCOMMENT(false, 3155, "가수 댓글 삭제에 실패하였습니다."),
    ALREADY_LIKE(false, 3161, "이미 좋아요가 반영되어 있습니다."),
    ALREADY_HATE(false, 3171, "이미 싫어요가 반영되어 있습니다."),
    FAILED_TO_POST_SINGERCOMMENTLIKE(false, 3183, "가수 댓글 좋아요 생성에 실패하였습니다."),
    FAILED_TO_DELETE_SINGERCOMMENTLIKE(false, 3185, "가수 댓글 좋아요 취소에 실패하였습니다."),
    FAILED_TO_POST_SINGERCOMMENTHATE(false, 3193, "가수 댓글 싫어요 생성에 실패하였습니다."),
    FAILED_TO_DELETE_SINGERCOMMENTHATE(false, 3195, "가수 댓글 싫어요 취소에 실패하였습니다."),
    NOT_FOUND_CURRENTPLAYMUSIC(false, 3200, "현재 재생 곡을 찾을 수 없습니다."),
    FAILED_TO_GET_CURRENTPLAYMUSIC(false, 3202, "현재 재생 곡 조회에 실패했습니다."),
    FAILED_TO_POST_CURRENTPLAYMUSIC(false, 3203, "현재 재생 곡 생성에 실패하였습니다."),
    FAILED_TO_GET_SINGERCHANNEL(false, 3212, "가수 채널 조회에 실패했습니다."),
    FAILED_TO_GET_SINGERRECOMMENT(false, 3222, "가수 대댓글 조회에 실패하였습니다."),
    FAILED_TO_POST_SINGERRECOMMENT(false, 3223, "가수 대댓글 생성에 실패하였습니다."),
    FAILED_TO_GET_CURRENTPLAYLIST(false, 3232, "현재 재생 목록 조회에 실패하였습니다."),
    FAILED_TO_POST_CURRENTPLAYLIST(false, 3233, "현재 재생 목록 생성에 실패하였습니다."),
    FAILED_TO_PATCH_CURRENTPLAYLIST(false, 3234, "현재 재생 목록 수정에 실패하였습니다."),
    FAILED_TO_DELETE_CURRENTPLAYLIST(false, 3235, "현재 재생 목록 삭제에 실패하였습니다."),
    FAILED_TO_GET_SINGERMUSIC(false, 3242, "가수 곡 목록 조회에 실패하였습니다."),

    // 4000 : Database 오류
    SERVER_ERROR(false, 4000, "서버와의 통신에 실패하였습니다."),
    DATABASE_ERROR(false, 4001, "데이터베이스 연결에 실패하였습니다.");

    // 5000 : 필요시 만들어서 쓰세요
    // 6000 : 필요시 만들어서 쓰세요

    private final boolean isSuccess;
    private final int code;
    private final String message;

    private BaseResponseStatus(boolean isSuccess, int code, String message) {
        this.isSuccess = isSuccess;
        this.code = code;
        this.message = message;
    }
}
